# Generated by ANSIBLE

eval "$(/opt/homebrew/bin/brew shellenv)"

export JAVA_HOME=$(/usr/libexec/java_home -v 11.0.20.1)
export ANDROID_SDK_ROOT="$HOMEBREW_PREFIX/share/android-commandlinetools"
# instead of : export ANDROID_SDK_ROOT="/Users/<YOUR_USER_NAME>/Library/Android/sdk"
export ANDROID_HOME="$HOMEBREW_PREFIX/share/android-commandlinetools"
# instead of : export ANDROID_HOME="/Users/<YOUR_USER_NAME>/Library/Android/sdk"
export ANDROID_AVD_HOME="~/.android/avd"
ADB_PATH="$HOMEBREW_PREFIX/share/android-commandlinetools/platform-tools/adb"
ANDROID_EMULATOR_PATH="$HOMEBREW_PREFIX/share/android-commandlinetools/emulator/"

export PATH="$ADB_PATH:$PATH"
export PATH="$ANDROID_EMULATOR_PATH:$PATH"

# Added by Toolbox App
export PATH="$PATH:$ANDROID_AVD_HOME:$ANDROID_ADB_HOME:$ANDROID_SDK/emulator/:$JAVA_HOME/bin:~/Library/Application Support/JetBrains/Toolbox/scripts"




