---
  - name: Add link to 11 java VM
    shell: sudo ln -sfn $HOMEBREW_PREFIX/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
    become: true

  - name: Check java version
    shell: java -version
    register: java_version

  - name: Print java version output
    debug:
      msg: "{{ java_version.stderr_lines }}"

  - name: Path to maven
    shell: mvn -v | grep -o '\/opt\/homebrew\/Cellar.*maven\/\d\.\d\.\d\/libexec' 
    register: mvn_home

  - name: Print maven path
    debug:
      msg: "{{ mvn_home.stdout }}"

  - name: Copy file settings.xml for Maven
    ansible.builtin.copy:
      src: resources/settings.xml
      dest: "{{ mvn_home.stdout }}/conf/settings.xml"