---
  - name: Copy file .zprofile
    ansible.builtin.copy:
      src: resources/.zprofile
      dest: ~/.zprofile
  
  - name: commet JAVA_HOME to ~/.zprofile
    ansible.builtin.lineinfile:
      path: ${HOME}/.zprofile
      regexp: '^export JAVA_HOME'
      line: '# export JAVA_HOME=$(/usr/libexec/java_home -v 11.0.20.1)'
      create: true

  - name: Check profile exists zprofile
    shell: source ~/.zprofile; cat ${HOME}/.zprofile
    register: profile_check 

  - name: Print zprofile
    debug:
      msg: "{{ profile_check.stdout }}"